-- 사원명부 조회 시스템 — 앱 계정·설정
-- 테이블 접두사: employee_
-- 사원 데이터는 public.ens_emp_roster 를 조회합니다.
-- Supabase SQL Editor에서 이 파일을 실행하세요.

-- 이전에 hrinfo_* 로 만든 경우 이름만 변경
DO $$
BEGIN
  IF to_regclass('public.hrinfo_users') IS NOT NULL
     AND to_regclass('public.employee_users') IS NULL THEN
    ALTER TABLE public.hrinfo_users RENAME TO employee_users;
  END IF;
  IF to_regclass('public.hrinfo_app_settings') IS NOT NULL
     AND to_regclass('public.employee_app_settings') IS NULL THEN
    ALTER TABLE public.hrinfo_app_settings RENAME TO employee_app_settings;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS employee_users (
  id text PRIMARY KEY,
  name text NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin', 'user')) DEFAULT 'user',
  department text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  password_must_change boolean NOT NULL DEFAULT false,
  permissions text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE employee_users
  ADD COLUMN IF NOT EXISTS password_must_change boolean NOT NULL DEFAULT false;

ALTER TABLE employee_users
  ADD COLUMN IF NOT EXISTS permissions text[] NOT NULL DEFAULT '{}';

CREATE INDEX IF NOT EXISTS employee_users_role_idx ON employee_users (role);
CREATE INDEX IF NOT EXISTS employee_users_active_idx ON employee_users (active);
ALTER TABLE employee_users DISABLE ROW LEVEL SECURITY;

-- 초기 관리자: hradmin / hradmin!! (첫 로그인 시 비밀번호 변경 필수)
INSERT INTO employee_users (id, name, password_hash, role, department, active, password_must_change) VALUES
  (
    'hradmin',
    '시스템 관리자',
    '$2b$10$BNsCYpx2inA4D82y7jNdAeZl1tQg8MRRgcXc7GwCDYtXxgNqwpS.u',
    'admin',
    '경영지원팀',
    true,
    true
  )
ON CONFLICT (id) DO NOTHING;

UPDATE employee_users
SET password_must_change = true
WHERE id = 'hradmin';

DELETE FROM employee_users WHERE id = 'admin';

CREATE TABLE IF NOT EXISTS employee_app_settings (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE employee_app_settings DISABLE ROW LEVEL SECURITY;

INSERT INTO employee_app_settings (key, value) VALUES
  ('idle_timeout_minutes', '30')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.employee_appointments (
  company_seq integer not null,
  emp_seq integer not null,
  sm_source_type integer not null,
  int_seq integer not null,
  emp_id text null,
  emp_name text null,
  sm_source_type_name text null,
  ord_seq integer null,
  ord_name text null,
  ord_date text null,
  ord_end_date text null,
  dept_seq integer null,
  dept_name text null,
  ord_dept_seq integer null,
  ord_dept_name text null,
  pos_seq integer null,
  pos_name text null,
  um_pg_seq integer null,
  um_pg_name text null,
  um_jp_seq integer null,
  um_jp_name text null,
  um_jd_seq integer null,
  um_jd_name text null,
  um_jo_seq integer null,
  um_jo_name text null,
  job_seq integer null,
  job_name text null,
  pu_seq integer null,
  pu_name text null,
  pt_seq integer null,
  pt_name text null,
  um_ws_seq integer null,
  um_ws_name text null,
  um_ps_seq integer null,
  um_ps_name text null,
  is_boss text null,
  is_ord_date_last text null,
  is_last text null,
  is_wk_ord text null,
  contents text null,
  remark text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  ent_date text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  um_ret_reason_name text null,
  um_work_time_type integer null,
  um_work_time_type_name text null,
  last_datetime timestamp with time zone null,
  last_user_name text null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_appointments_pkey primary key (company_seq, emp_seq, sm_source_type, int_seq)
);

CREATE TABLE IF NOT EXISTS public.employee_family (
  company_seq integer not null,
  emp_seq integer not null,
  family_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  family_name text null,
  family_resid_id text null,
  family_phone text null,
  um_rel_seq integer null,
  um_rel_name text null,
  sm_kin_ship_seq integer null,
  sm_kin_ship_name text null,
  um_sch_career_seq integer null,
  um_sch_career_name text null,
  occupation text null,
  sm_birth_type integer null,
  sm_birth_type_name text null,
  birth_date text null,
  reg_date text null,
  end_date text null,
  um_nation_seq integer null,
  um_nation_name text null,
  is_foreigner text null,
  is_same_roof text null,
  is_death text null,
  death_day text null,
  is_handi text null,
  um_handi_type integer null,
  um_handi_type_name text null,
  um_handi_grd integer null,
  um_handi_grd_name text null,
  handi_appdate text null,
  handi_healingday text null,
  is_nation_merit text null,
  is_pay_allow text null,
  is_med text null,
  disp_seq integer null,
  sm_disable_type integer null,
  sm_disable_type_name text null,
  sm_depend_type integer null,
  sm_depend_type_name text null,
  sm_per_birth_type integer null,
  sm_per_birth_type_name text null,
  is_senior text null,
  is_disabled text null,
  is_under_six text null,
  is_over_six text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  file_seq integer null,
  file_name text null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_family_pkey primary key (company_seq, emp_seq, family_seq)
);

CREATE TABLE IF NOT EXISTS public.employee_education (
  company_seq integer not null,
  emp_seq integer not null,
  academic_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  um_sch_career_seq integer null,
  um_sch_career_name text null,
  um_sch_seq integer null,
  um_sch_name text null,
  etc_sch_nm text null,
  um_major_depart integer null,
  um_major_depart_name text null,
  um_major_course integer null,
  um_major_course_name text null,
  major_course text null,
  um_minor_depart integer null,
  um_minor_depart_name text null,
  um_minor_course integer null,
  um_minor_course_name text null,
  minor_course text null,
  sm_day_night_type integer null,
  sm_day_night_type_name text null,
  ent_ym text null,
  grd_ym text null,
  um_degree_type integer null,
  um_degree_type_name text null,
  sm_degree_type integer null,
  sm_degree_type_name text null,
  degree_no text null,
  thesis_nm text null,
  loc text null,
  sm_university_type integer null,
  sm_university_type_name text null,
  is_last_sch_career text null,
  is_app_sch_career text null,
  disp_seq integer null,
  file_seq integer null,
  file_name text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_education_pkey primary key (company_seq, emp_seq, academic_seq)
);

CREATE TABLE IF NOT EXISTS public.employee_career (
  company_seq integer not null,
  emp_seq integer not null,
  career_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  pos_seq integer null,
  pos_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  co_nm text null,
  ent_date text null,
  ret_date text null,
  co_dept_name text null,
  jp_name text null,
  um_chrg_wk_seq integer null,
  um_chrg_wk_name text null,
  chrg_wk text null,
  area text null,
  bus_type text null,
  duty text null,
  is_grp text null,
  um_ret_reason integer null,
  um_ret_reason_name text null,
  app_car_term numeric null,
  app_car_per numeric null,
  um_career_type integer null,
  um_career_type_name text null,
  rem text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  file_seq integer null,
  file_name text null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_career_pkey primary key (company_seq, emp_seq, career_seq)
);

CREATE TABLE IF NOT EXISTS public.employee_languages (
  company_seq integer not null,
  emp_seq integer not null,
  linguistic_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  pos_seq integer null,
  pos_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  um_language_type integer null,
  um_language_type_name text null,
  um_auth_type integer null,
  um_auth_type_name text null,
  score numeric null,
  um_grade integer null,
  um_grade_name text null,
  beg_date text null,
  end_date text null,
  is_allow_pay text null,
  remark text null,
  file_seq integer null,
  file_name text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_languages_pkey primary key (company_seq, emp_seq, linguistic_seq)
);

CREATE TABLE IF NOT EXISTS public.employee_reward_penalty (
  company_seq integer not null,
  emp_seq integer not null,
  prz_pnl_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  um_jp_seq integer null,
  um_jp_name text null,
  um_jd_seq integer null,
  um_jd_name text null,
  um_pg_seq integer null,
  um_pg_name text null,
  pos_seq integer null,
  pos_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  sm_prz_pnl_type integer null,
  sm_prz_pnl_type_name text null,
  um_prz_pnl_seq integer null,
  um_prz_pnl_name text null,
  prz_pnl_fr_date text null,
  prz_pnl_to_date text null,
  sm_in_out_type integer null,
  sm_in_out_type_name text null,
  prz_pnl_reason text null,
  prz_pnl_inst text null,
  is_allow_deduc text null,
  remark text null,
  cancellation_date text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  file_seq integer null,
  file_name text null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_reward_penalty_pkey primary key (company_seq, emp_seq, prz_pnl_seq)
);

CREATE TABLE IF NOT EXISTS public.employee_licenses (
  company_seq integer not null,
  emp_seq integer not null,
  license_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  um_lic_seq integer null,
  um_lic_name text null,
  etc_lic_name text null,
  um_lic_group_seq integer null,
  um_lic_group_name text null,
  issue_inst text null,
  lic_no text null,
  acq_date text null,
  val_date text null,
  um_auth_type integer null,
  um_auth_type_name text null,
  score numeric null,
  um_grade integer null,
  is_allow_pay text null,
  is_law text null,
  rem text null,
  file_seq integer null,
  file_name text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_licenses_pkey primary key (company_seq, emp_seq, license_seq)
);

NOTIFY pgrst, 'reload schema';
