-- 사원 발령 이력 (ERP 동기화)

CREATE TABLE IF NOT EXISTS public.employee_appointments (
  company_seq integer not null,
  emp_seq integer not null,
  sm_source_type integer not null,
  int_seq integer not null,
  emp_id text null,
  emp_name text null,
  sm_source_type_name text null,
  ord_seq integer null,
  ord_name text null,
  ord_date text null,
  ord_end_date text null,
  dept_seq integer null,
  dept_name text null,
  ord_dept_seq integer null,
  ord_dept_name text null,
  pos_seq integer null,
  pos_name text null,
  um_pg_seq integer null,
  um_pg_name text null,
  um_jp_seq integer null,
  um_jp_name text null,
  um_jd_seq integer null,
  um_jd_name text null,
  um_jo_seq integer null,
  um_jo_name text null,
  job_seq integer null,
  job_name text null,
  pu_seq integer null,
  pu_name text null,
  pt_seq integer null,
  pt_name text null,
  um_ws_seq integer null,
  um_ws_name text null,
  um_ps_seq integer null,
  um_ps_name text null,
  is_boss text null,
  is_ord_date_last text null,
  is_last text null,
  is_wk_ord text null,
  contents text null,
  remark text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  ent_date text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  um_ret_reason_name text null,
  um_work_time_type integer null,
  um_work_time_type_name text null,
  last_datetime timestamp with time zone null,
  last_user_name text null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_appointments_pkey primary key (company_seq, emp_seq, sm_source_type, int_seq)
);
