-- 사원 가족 (ERP 동기화)

CREATE TABLE IF NOT EXISTS public.employee_family (
  company_seq integer not null,
  emp_seq integer not null,
  family_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  family_name text null,
  family_resid_id text null,
  family_phone text null,
  um_rel_seq integer null,
  um_rel_name text null,
  sm_kin_ship_seq integer null,
  sm_kin_ship_name text null,
  um_sch_career_seq integer null,
  um_sch_career_name text null,
  occupation text null,
  sm_birth_type integer null,
  sm_birth_type_name text null,
  birth_date text null,
  reg_date text null,
  end_date text null,
  um_nation_seq integer null,
  um_nation_name text null,
  is_foreigner text null,
  is_same_roof text null,
  is_death text null,
  death_day text null,
  is_handi text null,
  um_handi_type integer null,
  um_handi_type_name text null,
  um_handi_grd integer null,
  um_handi_grd_name text null,
  handi_appdate text null,
  handi_healingday text null,
  is_nation_merit text null,
  is_pay_allow text null,
  is_med text null,
  disp_seq integer null,
  sm_disable_type integer null,
  sm_disable_type_name text null,
  sm_depend_type integer null,
  sm_depend_type_name text null,
  sm_per_birth_type integer null,
  sm_per_birth_type_name text null,
  is_senior text null,
  is_disabled text null,
  is_under_six text null,
  is_over_six text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  file_seq integer null,
  file_name text null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_family_pkey primary key (company_seq, emp_seq, family_seq)
);
