-- 학력 / 경력 / 어학 / 상벌 (ERP 동기화)

CREATE TABLE IF NOT EXISTS public.employee_education (
  company_seq integer not null,
  emp_seq integer not null,
  academic_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  um_sch_career_seq integer null,
  um_sch_career_name text null,
  um_sch_seq integer null,
  um_sch_name text null,
  etc_sch_nm text null,
  um_major_depart integer null,
  um_major_depart_name text null,
  um_major_course integer null,
  um_major_course_name text null,
  major_course text null,
  um_minor_depart integer null,
  um_minor_depart_name text null,
  um_minor_course integer null,
  um_minor_course_name text null,
  minor_course text null,
  sm_day_night_type integer null,
  sm_day_night_type_name text null,
  ent_ym text null,
  grd_ym text null,
  um_degree_type integer null,
  um_degree_type_name text null,
  sm_degree_type integer null,
  sm_degree_type_name text null,
  degree_no text null,
  thesis_nm text null,
  loc text null,
  sm_university_type integer null,
  sm_university_type_name text null,
  is_last_sch_career text null,
  is_app_sch_career text null,
  disp_seq integer null,
  file_seq integer null,
  file_name text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_education_pkey primary key (company_seq, emp_seq, academic_seq)
);

CREATE TABLE IF NOT EXISTS public.employee_career (
  company_seq integer not null,
  emp_seq integer not null,
  career_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  pos_seq integer null,
  pos_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  co_nm text null,
  ent_date text null,
  ret_date text null,
  co_dept_name text null,
  jp_name text null,
  um_chrg_wk_seq integer null,
  um_chrg_wk_name text null,
  chrg_wk text null,
  area text null,
  bus_type text null,
  duty text null,
  is_grp text null,
  um_ret_reason integer null,
  um_ret_reason_name text null,
  app_car_term numeric null,
  app_car_per numeric null,
  um_career_type integer null,
  um_career_type_name text null,
  rem text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  file_seq integer null,
  file_name text null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_career_pkey primary key (company_seq, emp_seq, career_seq)
);

CREATE TABLE IF NOT EXISTS public.employee_languages (
  company_seq integer not null,
  emp_seq integer not null,
  linguistic_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  pos_seq integer null,
  pos_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  um_language_type integer null,
  um_language_type_name text null,
  um_auth_type integer null,
  um_auth_type_name text null,
  score numeric null,
  um_grade integer null,
  um_grade_name text null,
  beg_date text null,
  end_date text null,
  is_allow_pay text null,
  remark text null,
  file_seq integer null,
  file_name text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_languages_pkey primary key (company_seq, emp_seq, linguistic_seq)
);

CREATE TABLE IF NOT EXISTS public.employee_reward_penalty (
  company_seq integer not null,
  emp_seq integer not null,
  prz_pnl_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  um_jp_seq integer null,
  um_jp_name text null,
  um_jd_seq integer null,
  um_jd_name text null,
  um_pg_seq integer null,
  um_pg_name text null,
  pos_seq integer null,
  pos_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  sm_prz_pnl_type integer null,
  sm_prz_pnl_type_name text null,
  um_prz_pnl_seq integer null,
  um_prz_pnl_name text null,
  prz_pnl_fr_date text null,
  prz_pnl_to_date text null,
  sm_in_out_type integer null,
  sm_in_out_type_name text null,
  prz_pnl_reason text null,
  prz_pnl_inst text null,
  is_allow_deduc text null,
  remark text null,
  cancellation_date text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  file_seq integer null,
  file_name text null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_reward_penalty_pkey primary key (company_seq, emp_seq, prz_pnl_seq)
);
