-- 자격증 (ERP 동기화)

CREATE TABLE IF NOT EXISTS public.employee_licenses (
  company_seq integer not null,
  emp_seq integer not null,
  license_seq integer not null,
  emp_id text null,
  emp_name text null,
  dept_seq integer null,
  dept_name text null,
  ent_ret_type_seq integer null,
  ent_ret_type_name text null,
  um_emp_type integer null,
  um_emp_type_name text null,
  um_lic_seq integer null,
  um_lic_name text null,
  etc_lic_name text null,
  um_lic_group_seq integer null,
  um_lic_group_name text null,
  issue_inst text null,
  lic_no text null,
  acq_date text null,
  val_date text null,
  um_auth_type integer null,
  um_auth_type_name text null,
  score numeric null,
  um_grade integer null,
  is_allow_pay text null,
  is_law text null,
  rem text null,
  file_seq integer null,
  file_name text null,
  dummy1 text null,
  dummy2 text null,
  dummy3 text null,
  dummy4 text null,
  dummy5 text null,
  dummy6 integer null,
  dummy7 integer null,
  dummy8 integer null,
  dummy9 integer null,
  dummy10 integer null,
  synced_at timestamp with time zone not null default now(),
  constraint employee_licenses_pkey primary key (company_seq, emp_seq, license_seq)
);
